###############################################
depth_splitname:
    folder: /data/vidar/save
    naming: splitname
    rgb: [tgt]
    depth: [viz,npz]
###############################################
